### ISSUE TITLE
Does not work in Firefox

### ISSUE THREAD

**Issue by antonpirker** [getsentry/cookie-sync#22]
### Environment

What version are you running? Etc.
MacOS Ventura
Firefox 117.0.1

### Steps to Reproduce

- Installed Cookie Sync extension from here: https://addons.mozilla.org/en-US/firefox/addon/sentry-cookie-sync/
- Visiting this URL in firefox: https://sentry-sdks.sentry.io/issues/?project=5461230&statsPeriod=1h (So I am logged in with my Sentry Google account)
- Open the Extension
  ![Screenshot 2023-09-19 at 09 30 34](https://github.com/getsentry/cookie-sync/assets/202325/54c37d7a-cf17-41e3-ae9a-c829a41a168c)
- Click on "Sync cookies now"
- There is a "Something went wrong".
  ![Screenshot 2023-09-19 at 09 30 40](https://github.com/getsentry/cookie-sync/assets/202325/e07f8439-5bf7-4bcb-a75f-6a3ec2b6f3e2)

### Expected Result

Something other than "Something went wrong".

### Actual Result

"something went wrong" see above

**Comment by ryan953** [comment]
I think this is a problem with the `localhost` domain. It's trying to assign cookies into subdomains like `test-az.localhost` but that's not supported by the browsers, so things are failing.

In https://github.com/getsentry/cookie-sync/commit/112f2d48c8f8844207c664da7a39066a65a68354 I removed support for localhost, and I've also put up a docs change https://github.com/getsentry/develop/pull/1037 to encourage `*.dev.getsentry.net` instead.
